# Menu configuration.
# menu:
#   home: /
#   archives: /archives

# Favicon
favicon: /favicon.ico

# Avatar (put the image into next/source/images/)
# can be any image format supported by web browsers (JPEG,PNG,GIF,SVG,..)
avatar: "https://avatars1.githubusercontent.com/u/16848310?s=400&u=2fdf9659bfec8834a09b72900e061ebf044a24ff&v=4"

# Code highlight theme
# available: normal | night | night eighties | night blue | night bright
highlight_theme: normal

# Fancybox for image gallery
fancybox: true

# Specify the date when the site was setup
since: 2017

# social:
#   GitHub: https://github.com/
#   douban: https://www.douban.com/people/timor_java/
# theme: next

language: zh-Hans

title: Tisp
# subtitle: 这是一只会唱歌的程序猿
# description: 开始不用脑子装东西,好记性不如烂笔头
author: 皮聪
date_format: YYYY-MM-DD

theme: yilia

deploy:
  type: git
  repo: git@github.com:picong/picong.github.io.git
  branch: master

jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true
